
CREATE TABLE IF NOT EXISTS ORDERTABLE (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
 CUSTOMER_NAME VARCHAR(250),
  ORDER_DATE DATE,
  SHIPPING_ADDRESS VARCHAR(250),
  ORDERITEM_CODE VARCHAR(20),
  TOTAL NUMBER(20,2)
);

INSERT INTO ORDERTABLE (CUSTOMER_NAME, ORDER_DATE, SHIPPING_ADDRESS,ORDERITEM_CODE,TOTAL) VALUES
  ('TOM',TO_DATE('17/12/2015', 'DD/MM/YYYY'),'MARYMOUNT','A0001','200');
  