DROP TABLE IF EXISTS ORDERITEM;

CREATE TABLE ORDERITEM (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  PRODUCT_CODE VARCHAR(250),
  PRODUCT_NAME VARCHAR(250),
  QUANTITY BIGINT
);

INSERT INTO ORDERITEM (PRODUCT_CODE, PRODUCT_NAME, QUANTITY) VALUES
  ('A00001', 'CHOCOLATE', 2),
  ('A00002', 'EGG', 1),
  ('A00003', 'RICE', 1);